export const INITIATE_API = 'INITIATE_API';
export const INITIATE_API_SUCCESS = 'INITIATE_API_SUCCESS';
export const INITIATE_API_FAILED = 'INITIATE_API_FAILED';

export const MEMBER_STATE_DATA = 'MEMBER_STATE_DATA';
export const MEMBER_STATE_SUCCESS = 'MEMBER_STATE_SUCCESS';
export const MEMBER_STATE_FAILED = 'MEMBER_STATE_FAILED';

export const UNIVERSAL_FEED_DATA = 'UNIVERSAL_FEED_DATA';
export const UNIVERSAL_FEED_FAILED = 'UNIVERSAL_FEED_FAILED';
export const UNIVERSAL_FEED_SUCCESS = 'UNIVERSAL_FEED_SUCCESS';
