export const INITIATE_API = 'INITIATE_API';
export const INITIATE_API_SUCCESS = 'INITIATE_API_SUCCESS';
export const INITIATE_API_FAILED = 'INITIATE_API_FAILED';

export const MEMBER_STATE_DATA = 'MEMBER_STATE_DATA';
export const MEMBER_STATE_SUCCESS = 'MEMBER_STATE_SUCCESS';
export const MEMBER_STATE_FAILED = 'MEMBER_STATE_FAILED';

export const UNIVERSAL_FEED_DATA = 'UNIVERSAL_FEED_DATA';
export const UNIVERSAL_FEED_FAILED = 'UNIVERSAL_FEED_FAILED';
export const UNIVERSAL_FEED_SUCCESS = 'UNIVERSAL_FEED_SUCCESS';

export const LIKE_POST= 'LIKE_POST';
export const LIKE_POST_FAILED = 'LIKE_POST_FAILED';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_STATE = 'LIKE_POST_STATE';

export const SAVE_POST= 'SAVE_POST';
export const SAVE_POST_FAILED = 'SAVE_POST_FAILED';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_STATE = 'SAVE_POST_STATE';

export const REPORT_TAGS_DATA= 'REPORT_TAGS_DATA';
export const REPORT_TAGS_FAILED = 'REPORT_TAGS_FAILED';
export const REPORT_TAGS_SUCCESS = 'REPORT_TAGS_SUCCESS';

export const POST_REPORT= 'POST_REPORT';
export const POST_REPORT_FAILED = 'POST_REPORT_FAILED';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';

export const POST_DELETE= 'POST_DELETE';
export const POST_DELETE_FAILED = 'POST_DELETE_FAILED';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const DELETE_POST_STATE = 'DELETE_POST_STATE';

export const PIN_POST= 'PIN_POST';
export const PIN_POST_FAILED = 'PIN_POST_FAILED';
export const PIN_POST_SUCCESS = 'PIN_POST_SUCCESS';
export const PIN_POST_STATE = 'PIN_POST_STATE';

export const AUTO_PLAY_POST_VIDEO = 'AUTO_PLAY_POST_VIDEO'

export const POST_LIKES_DATA = 'POST_LIKES_DATA';
export const POST_LIKES_FAILED = 'POST_LIKES_FAILED';
export const POST_LIKES_SUCCESS = 'POST_LIKES_SUCCESS';
export const POST_LIKES_CLEAR = 'POST_LIKES_CLEAR';

export const DECODE_URL_DATA = 'DECODE_URL_DATA';
export const DECODE_URL_FAILED = 'DECODE_URL_FAILED';
export const DECODE_URL_SUCCESS = 'DECODE_URL_SUCCESS';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const UPLOAD_ATTACHMENTS = 'UPLOAD_ATTACHMENTS';
export const CLEAR_FEED = 'CLEAR_FEED';