export default {
  $COLORS: {
    darkTextColor: '#000000',
    lightGreyTextColor: '#00000077',
    darkGreyTextColor: '#00000099',
    whiteTextColor: '#ffffff',
    RED: '#ff0000',
    carouselActiveItem: '#5046E5',
    carouselInActiveItem: '#e0e0e0',
    postDescriptionTextColor: '#666666',
  },
  $FONT_SIZES: {
    XS: 10,
    SMALL: 12,
    MEDIUM: 14,
    LARGE: 16,
    XL: 18,
    XXL: 20,
  },
  $FONT_WEIGHTS: {
    LIGHT: '200' as const,
    REGULAR: '400' as const,
    MEDIUM: '500' as const,
    BOLD: '700' as const,
  },
  $FONT_FAMILY: {
    LIGHT: 'Roboto-Light',
    THIN: 'Roboto-Thin',
    REGULAR: 'Roboto-Regular',
    MEDIUM: 'Roboto-Medium',
    BOLD: 'Roboto-Bold',
    BLACK: 'Roboto-Black',
  },
  $BACKGROUND_COLORS: {
    LIGHT: '#ffffff',
    DARK: '#000000',
    DARKTRANSPARENT: '#00000088',
  },
  $BORDER_COLORS: {
    LIGHT: '#00000066',
  },
  $MARGINS: {
    XS: 5,
    SMALL: 10,
    MEDIUM: 15,
    LARGE: 20,
    XL: 25,
    XXL: 30,
  },
  $PADDINGS: {
    XS: 5,
    SMALL: 10,
    MEDIUM: 15,
    LARGE: 20,
    XL: 25,
    XXL: 30,
  },
  $LMLoaderSizeiOS: 10,
  $LMLoaderSizeAndroid: 25,
};
